### ISSUE TITLE
Pose issues (offline mode)

### ISSUE THREAD

**Issue by nepfaff** [jc211/NeRFCapture#4]
Hi, I used NeRFCapture to capture a scene with an iPhone 12 Pro. From the instantNGP debug visualization, the camera poses seem to be scaled weirdly (see screenshot). The scene did not converge.

![image](https://user-images.githubusercontent.com/53228351/227326217-3d264299-c918-4f5c-8c67-abbe7b2027f8.png)

The data zip can be downloaded from [here](https://mitprod-my.sharepoint.com/:u:/g/personal/nepfaff_mit_edu/EZxgyg3_nKBMk7WDo-wZSEIBKgo_E9Ldg50LDBK0AqBgsw?e=mflVor).

**Comment by jc211** [comment]
Hey! The dataset converged on my end so poses seem ok. Couple of things might help:
1. Reset the coordinate system of NeRFCapture over the object so that the unitbox is centered there (you should be able to see the origin in the app)
2. Turn on depth supervision
3. Change the aabb scale so that the object fills more of the unit box. You do this in the transforms.json file


![mustard](https://user-images.githubusercontent.com/29726242/227438784-034f0657-4a26-4847-a447-2fc201703cf7.gif)

**Comment by nepfaff** [comment]
Thanks for these tips! I got it working now.
My main issue actually turned out to be that I hadn't updated instant-ngp for months and there seem to be some changes that make it work. So nothing todo with your implementation :)
